version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      # Security updates
      - dependency-name: brakeman
        dependency-type: direct
      # Internal gems
      - dependency-name: "govuk*"
        dependency-type: direct
      - dependency-name: "rubocop-govuk"
        dependency-type: direct
      - dependency-name: "gds-api-adapters"
        dependency-type: direct
      - dependency-name: "gds-sso"
        dependency-type: direct
      - dependency-name: plek
        dependency-type: direct
      # Framework gems
      - dependency-name: factory_bot_rails
        dependency-type: direct
      - dependency-name: rails
        dependency-type: direct
      - dependency-name: rails-controller-testing
        dependency-type: direct
      # Gems with framework dependencies
      - dependency-name: inherited_resources
        dependency-type: direct
      - dependency-name: mongoid
        dependency-type: direct
