default: &default
  adapter: postgis
  encoding: unicode
  pool: 12
  template: template0
  schema_search_path: public

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"]%>

test:
  <<: *default
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"]%>
