name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - "Jenkinsfile"
      - ".git**"
  pull_request:

jobs:
  security-analysis:
    name: Security Analysis
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yml@main

  lint-ruby:
    name: Lint Ruby
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yml@main

  pact-tests:
    name: Run Pact tests
    uses: ./.github/workflows/pact-verify.yml
    with:
      ref: ${{ github.ref }}

  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest

    services:
      postgis:
        image: postgis/postgis:14-master
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      TEST_DATABASE_URL: postgis://postgres:postgres@127.0.0.1:5432/test

    steps:
      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@main

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Precompile assets
        uses: alphagov/govuk-infrastructure/.github/actions/precompile-rails-assets@main

      - name: Initialize database
        run: bundle exec rails db:setup

      - name: Run Minitest
        run: bundle exec rake test

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest

    services:
      postgis:
        image: postgis/postgis:14-master
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      TEST_DATABASE_URL: postgis://postgres:postgres@127.0.0.1:5432/test

    steps:
      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@main

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Precompile assets
        uses: alphagov/govuk-infrastructure/.github/actions/precompile-rails-assets@main

      - name: Initialize database
        run: bundle exec rails db:setup

      - name: Run cucumber
        run: bundle exec rails cucumber
